// Data dummy produk — nanti bisa diganti harga, deskripsi, dan gambar asli

const COMPANY = {
  name: "CV Mitra Mutiara Kencana",
  tagline: "Pengadaan Barang & Jasa Acara",
  //phone: "085161970147",
  phone: "08131323187",
  // Format lokal untuk ditampilkan; konversi ke 62... dilakukan di getWhatsAppNumber()
  //whatsapp: "085161970147",
  whatsapp: "08131323187",
  email: "mitramutiarakencana@gmail.com",
  address: "Komp. Mutiara Platinum GMP 15, Pulo Gebang, Cakung, Jakarta Timur - DKI Jakarta",
};

const CATEGORIES = [
  {
    slug: "souvenir-atk",
    name: "Souvenir & ATK",
    shortName: "Souvenir & ATK",
    description: "Souvenir custom dan alat tulis kantor untuk keperluan kantor, event, dan gift.",
    image: "https://placehold.co/600x400/0A2A5E/ffffff?text=Souvenir+%26+ATK",
    hideSubCategoryFilter: true,
    // Harga disembunyikan di card grid, tetap tampil di halaman detail
    hidePriceOnCard: true,
  },
  {
    slug: "sewa-perlengkapan",
    name: "Sewa Perlengkapan Acara",
    shortName: "Perlengkapan",
    description: "Sewa meja, kursi, dan perlengkapan pendukung acara.",
    image: "https://placehold.co/600x400/4A90D9/ffffff?text=Perlengkapan+Acara",
    // Harga disembunyikan di card grid, tetap tampil di halaman detail
    hidePriceOnCard: true,
  },
  {
    slug: "sewa-tenda",
    name: "Sewa Tenda Acara",
    shortName: "Tenda",
    description: "Sewa tenda dekorasi, roder, kerucut, bazar, dan jenis tenda lainnya.",
    image: "https://placehold.co/600x400/0A2A5E/ffffff?text=Sewa+Tenda",
    hideSubCategoryFilter: true,
    // Harga disembunyikan di card grid, tetap tampil di halaman detail
    hidePriceOnCard: true,
  },
  {
    slug: "catering",
    name: "Catering",
    shortName: "Catering",
    description: "Paket catering untuk rapat, gathering, dan acara resmi.",
    image: "https://placehold.co/600x400/4A90D9/ffffff?text=Catering",
    // Label tab spesifikasi di halaman detail; kalau kosong dipakai "Spesifikasi"
    specLabel: "Menu",
  },
];

const PRODUCTS = [
  // Souvenir & ATK
  {
    id: "sou-001",
    kategori: "souvenir-atk",
    subKategori: "Alat Tulis Kantor",
    nama: "Pengadaan ATK",
    deskripsi:
      "Layanan Pengadaan Barang ATK menyediakan berbagai kebutuhan alat tulis kantor (ATK) secara lengkap untuk mendukung operasional perusahaan, instansi pemerintah, sekolah, maupun organisasi. Produk yang disediakan meliputi kertas, pulpen, pensil, map, binder, tinta printer, stapler, amplop, buku, serta berbagai perlengkapan administrasi lainnya dengan kualitas terjamin, harga yang kompetitif, dan proses pengadaan yang cepat sesuai kebutuhan.\n\nKami melayani pengadaan ATK dalam jumlah kecil maupun besar dengan layanan yang profesional dan terpercaya. Konsultasikan kebutuhan pengadaan ATK Anda melalui WhatsApp kami untuk mendapatkan rekomendasi produk, penawaran terbaik, serta solusi pengadaan yang sesuai dengan kebutuhan dan anggaran Anda.",
    spesifikasi: [
      "Jenis Produk: Berbagai macam ATK dan perlengkapan perkantoran",
      "Merek: Menyesuaikan kebutuhan pemesan",
      "Ukuran: Menyesuaikan jenis produk",
      "Kondisi barang: Baru, Original, dan Berkualitas",
      "Melayani pengadaan dalam jumlah kecil maupun besar",
      "Pengadaan dapat disesuaikan dengan spesifikasi dan anggaran pelanggan",
      "Pengemasan rapi dan aman",
      "Pengiriman ke lokasi pelanggan sesuai kesepakatan",
    ],
    harga: "Harga menyesuaikan Jenis, Merek, Spesifikasi, dan Jumlah Pesanan",
    satuan: "",
    gambar: "assets/images/products/atk/pb1.png",
  },
  {
    id: "sou-002",
    kategori: "souvenir-atk",
    subKategori: "Percetakan",
    nama: "Pengadaan Percetakan",
    deskripsi: "Jasa Pengadaan Barang Percetakan merupakan layanan penyediaan berbagai kebutuhan cetak untuk keperluan perkantoran, instansi, perusahaan, sekolah, organisasi, maupun kegiatan lainnya. Produk yang dapat disediakan meliputi berbagai kebutuhan percetakan seperti kartu nama, kop surat, amplop, brosur, flyer, poster, banner, spanduk, undangan, sertifikat, kalender, buku, booklet, map, stiker, label, nota, formulir, dan berbagai produk cetak lainnya sesuai kebutuhan. \n\nPengadaan dilakukan berdasarkan spesifikasi dan kebutuhan pemesan, meliputi jenis produk, ukuran, bahan, desain, jumlah, finishing, serta ketentuan lainnya. Produk dapat disesuaikan dengan kebutuhan dan anggaran, dengan proses pengerjaan memperhatikan kualitas hasil cetak, ketepatan spesifikasi, jumlah pesanan, dan waktu penyelesaian.",
    spesifikasi: [
      "Produk meliputi kartu nama, kop surat, amplop, brosur, flyer, poster, banner, spanduk, undangan, sertifikat, kalender, buku, booklet, map, stiker, label, nota, formulir, dan produk percetakan lainnya.",
      "Ukuran menyesuaikan jenis produk dan kebutuhan pemesan.",
      "Bahan/Media meliputi HVS, Art Paper, Art Carton, Ivory, Duplex, Vinyl, Banner, Sticker, dan bahan lainnya sesuai kebutuhan.",
      "Cetak: Full Color atau Hitam Putih.",
      "Finishing: Potong, Laminasi, Jilid, Lipat, Pond, dan finishing lainnya sesuai jenis produk.",
      "Desain: Menggunakan desain dari pemesan atau dapat disesuaikan berdasarkan kebutuhan.",
      "Kemasan: Disesuaikan dengan jenis dan jumlah produk.",
      "Waktu Pengerjaan: Menyesuaikan jenis produk, jumlah pesanan, dan tingkat kesulitan pengerjaan.",
    ],
    harga: "Harga Menyesuaikan Jenis, Bahan, dan Jumlah Pesanan",
    satuan: "",
    gambar: "assets/images/products/atk/pb2.png",
  },
  {
    id: "sou-003",
    kategori: "souvenir-atk",
    subKategori: "Souvenir",
    nama: "Pengadaan Souvenir",
    deskripsi: "Layanan Pengadaan Souvenir menyediakan berbagai pilihan souvenir berkualitas untuk kebutuhan perusahaan, instansi pemerintah, organisasi, sekolah, maupun acara pribadi. Kami melayani pengadaan berbagai jenis souvenir seperti tumbler, mug, payung, tote bag, pulpen, notebook, buku agenda, flashdisk, plakat, gift set, serta berbagai merchandise lainnya yang dapat disesuaikan dengan kebutuhan dan identitas pelanggan. \n\nKami melayani pemesanan dalam jumlah kecil maupun besar dengan pilihan desain, bahan, dan metode branding sepertilaser engraving, dan emboss (menyesuaikan jenis produk).",
    spesifikasi: [
      "Menyediakan berbagai jenis souvenir dan merchandise sesuai kebutuhan pelanggan.",
      "Produk meliputi tote bag, pulpen, notebook, buku agenda, flashdisk, plakat, gift set, dan merchandise lainnya.",
      "Tersedia berbagai pilihan bahan, ukuran, warna, dan model.",
      "Kondisi barang: Baru, Original, dan Berkualitas",
      "Mendukung kustomisasi desain sesuai identitas perusahaan atau instansi.",
      "Opsi branding meliputi sablon, bordir, printing, UV printing, laser engraving, dan emboss (menyesuaikan jenis produk).",
      "Melayani pengadaan dalam jumlah kecil maupun besar.",
      "Pengemasan rapi dan aman.",
    ],
    harga: "Harga Menyesuaikan Jenis, Bahan, dan Jumlah Pesanan",
    satuan: "",
    gambar: "assets/images/products/atk/pb3.png",
  },


  // Sewa Perlengkapan Acara
  {
    id: "per-001",
    kategori: "sewa-perlengkapan",
    subKategori: "Meja",
    nama: "Meja Bulat",
    deskripsi:
      "Lengkapi Penataan Acara dengan Tampilan yang Rapi dan Elegan. Kami menyediakan layanan sewa meja bulat beserta cover untuk berbagai kebutuhan acara, seperti pernikahan, seminar, rapat, jamuan makan, acara perusahaan, kegiatan pemerintahan, hingga acara keluarga. Tersedia dalam berbagai pilihan ukuran meja dan warna cover yang dapat disesuaikan dengan tema acara. Didukung oleh layanan pengiriman, pemasangan, dan pengambilan yang profesional, kami memastikan setiap meja tersaji dengan rapi sehingga menciptakan suasana acara yang nyaman, tertata, dan representatif.",
    spesifikasi: [
      "Jenis: Meja Bulat",
      "Dimensi: Ø120cm / Ø150cm, plywood tebal 18mm, rangka aluminium",
      "Material Rangka: Plywood 18mm, Rangka aluminium",
      "Material Cover: Satin 230g/m², anti kerut dan Spandex 350g/m², stretch fit",
      "Pilihan Warna Cover: 15 pilihan warna",
      "Durasi Pemasangan: 5-10 menit per cover",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Penggantian cover di lokasi jika rusak/cacat/kotor",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/perlengkapan-acara/meja-bulat.png",
  },
  {
    id: "per-002",
    kategori: "sewa-perlengkapan",
    subKategori: "Meja",
    nama: "Meja Kotak",
    deskripsi:
      "Solusi Praktis untuk Berbagai Kebutuhan Acara. Kami menyediakan layanan sewa meja kotak yang cocok digunakan untuk berbagai kegiatan, seperti seminar, rapat, pameran, bazar, pelatihan, acara perusahaan, kegiatan pemerintahan, hingga acara keluarga. Tersedia dalam berbagai ukuran yang dapat disesuaikan dengan kebutuhan dan tata letak acara. Didukung oleh layanan pengiriman, penataan, dan pengambilan yang profesional, kami memastikan setiap meja dalam kondisi bersih, kokoh, dan siap digunakan sehingga mendukung kelancaran setiap kegiatan.",
    spesifikasi: [
     "Jenis: Meja Kotak",
      "Dimensi: 60 x 60cm / 80 x 80cm",
      "Material Rangka: Plywood 18mm, Rangka aluminium",
      "Material Cover: Satin 230g/m², anti kerut dan Spandex 350g/m², stretch fit",
      "Pilihan Warna Cover: 15 pilihan warna",
      "Durasi Pemasangan: 5-10 menit per cover",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Penggantian cover di lokasi jika rusak/cacat/kotor",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/perlengkapan-acara/meja-kotak.png",
  },
  {
    id: "per-003",
    kategori: "sewa-perlengkapan",
    subKategori: "Kursi",
    nama: "Kursi Futura",
    deskripsi:
      "Pilihan Praktis untuk Berbagai Acara. Kami menyediakan layanan sewa kursi futura beserta cover untuk kebutuhan pernikahan, seminar, rapat, pengajian, acara perusahaan, kegiatan pemerintahan, dan acara lainnya. Tersedia berbagai pilihan warna cover yang dapat disesuaikan dengan tema acara, didukung layanan pengiriman, penataan, dan pengambilan secara profesional.",
    spesifikasi: [
      "Jenis: Kursi Futura",
      "Dimensi: P 40 x L 40 x T 85",
      "Pilihan Warna Cover: Hitam dan Putih",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Penggantian cover di lokasi jika rusak/cacat/kotor",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/perlengkapan-acara/kursi-futura.png",
  },
 

  // Sewa Tenda Acara
  {
    id: "ten-001",
    kategori: "sewa-tenda",
    subKategori: "Tenda Standar",
    nama: "Tenda Plafon/Standar",
    deskripsi:
      "Solusi Praktis untuk Berbagai Kebutuhan Acara. Kami menyediakan layanan sewa tenda plafon/standar yang cocok digunakan untuk acara pernikahan, lamaran, khitanan, aqiqah, pengajian, ulang tahun, kegiatan perusahaan, pemerintahan, maupun acara lainnya. Tenda standar merupakan pilihan yang mengutamakan fungsi, kenyamanan, dan tampilan yang rapi, dilengkapi dengan plafon yang menutupi rangka bagian atas tenda sehingga memberikan kesan lebih bersih, nyaman, dan representatif. Tersedia dalam berbagai ukuran sesuai kebutuhan, dengan layanan pemasangan dan pembongkaran yang dikerjakan secara profesional untuk mendukung kelancaran berbagai jenis kegiatan.",
    spesifikasi: [
      "Jenis Tenda: Tenda Plafon/Standar",
      "Dimensi: ",
      "Spesifikasi Material:",
      "Spesifikasi Rangka:",
      "Durasi Pemasangan: 3 - 4 Jam",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Pemasangan",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/tenda/1-tenda-plafon.png",
  },
  {
    id: "ten-002",
    kategori: "sewa-tenda",
    subKategori: "Tenda Dekorasi",
    nama: "Tenda Dekorasi",
    deskripsi:
      "Hadirkan Tampilan Acara yang Lebih Menarik dan Profesional. Kami menyediakan layanan sewa tenda dekorasi untuk berbagai kebutuhan acara, seperti pernikahan, lamaran, khitanan, aqiqah, ulang tahun, pengajian, acara perusahaan, hingga kegiatan pemerintahan. Tersedia berbagai pilihan model tenda dan konsep dekorasi yang dapat disesuaikan dengan tema serta kebutuhan acara. Paket sewa dapat dilengkapi dengan plafon tenda, tirai samping, dekorasi kain (drapery), lighting, serta berbagai ornamen dekoratif lainnya, sesuai dengan paket dan kebutuhan pelanggan. Didukung oleh tim yang berpengalaman, kami memberikan layanan pemasangan dan pembongkaran secara profesional sehingga menciptakan suasana acara yang rapi, nyaman, elegan, dan berkesan.",
    spesifikasi: [
      "Jenis Tenda: Dekorasi",
      "Dimensi: 4 x 6 dan 5 x 5",
      "Spesifikasi Material: PVC 650 g/m² (White, Transparent, Opaque)",
      "Spesifikasi Rangka: Aluminium anodized profil 60 x 60mm",
      "Durasi Pemasangan: 3 - 4 Jam",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Pemasangan",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/tenda/2-tenda-dekorasi.png",
  },
  {
    id: "ten-003",
    kategori: "sewa-tenda",
    subKategori: "Tenda Roder",
    nama: "Tenda Roder/Gudang",
    deskripsi:
      "Pilihan Tepat untuk Acara Berskala Besar. Kami menyediakan layanan sewa tenda roder dengan struktur rangka aluminium yang kokoh dan penutup berkualitas tinggi, sehingga ideal digunakan untuk berbagai kegiatan, seperti pameran, konser, pernikahan, acara perusahaan, kegiatan pemerintahan, gudang sementara, hingga acara berskala besar lainnya. Tersedia dalam berbagai ukuran yang dapat disesuaikan dengan kebutuhan lokasi dan kapasitas acara. Didukung oleh tim yang berpengalaman, kami memberikan layanan pemasangan dan pembongkaran secara profesional untuk menghadirkan area acara yang aman, nyaman, dan representatif.",
    spesifikasi: [
      "Jenis Tenda: Roder",
      "Dimensi: 3 x 3 dan 6 x 6",
      "Spesifikasi Material: PVC Tarpaulin 650g/m²",
      "Spesifikasi Rangka: Aluminium anodized 50 x 50mm",
      "Durasi Pemasangan: 3 - 4 Jam",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Pemasangan",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/tenda/3-tenda-roder.png",
  },
  {
    id: "ten-004",
    kategori: "sewa-tenda",
    subKategori: "Tenda Sarnafil",
    nama: "Tenda Kerucut/Sarnafil",
    deskripsi:
      "Hadirkan Ruang Acara yang Luas dan Elegan. Kami menyediakan layanan sewa tenda sarnavil yang cocok digunakan untuk berbagai kegiatan outdoor, seperti pernikahan, pameran, bazar, acara perusahaan, kegiatan pemerintahan, konser, maupun acara lainnya. Tenda sarnavil memiliki konstruksi yang kokoh, desain yang fungsional, serta tersedia dalam berbagai ukuran yang dapat disesuaikan dengan kebutuhan lokasi dan kapasitas acara. Didukung oleh tim yang berpengalaman, kami memberikan layanan pemasangan dan pembongkaran secara profesional sehingga menciptakan area acara yang aman, nyaman, dan representatif.",
    spesifikasi: [
      "Jenis Tenda: Sarnafil/Kerucut",
      "Dimensi: 5 x 5m per modul",
      "Spesifikasi Material: PVC 750g/m² UV-resistant",
      "Spesifikasi Rangka: Baja Galvanis 100 x 100mm",
      "Tinggi Puncak: 4,5m",
      "Durasi Pemasangan: 2 - 3 Jam/modul",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Pemasangan",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/tenda/4-tenda-sarnafil.png",
  },
  {
    id: "ten-005",
    kategori: "sewa-tenda",
    subKategori: "Tenda Bazaar",
    nama: "Tenda Bazaar Standar",
    deskripsi:
      "Solusi Praktis untuk Berbagai Kegiatan dan Event. Kami menyediakan layanan sewa tenda bazaar yang cocok digunakan untuk kegiatan pameran, bazar, promosi produk, UMKM, festival, acara perusahaan, kegiatan pemerintahan, maupun berbagai acara lainnya. Tenda bazaar dirancang dengan konstruksi yang kokoh, mudah dipasang, serta tersedia dalam berbagai ukuran sesuai kebutuhan lokasi dan kegiatan. Didukung oleh tim yang berpengalaman, kami memberikan layanan pemasangan dan pembongkaran secara profesional untuk menghadirkan area usaha atau kegiatan yang nyaman, rapi, dan representatif.",
    spesifikasi: [
      "Jenis Tenda: Bazaar Standar",
      "Dimensi: 2m x 2m dan 3m x 3m",
      "Spesifikasi Material: PVC 450 - 650g/m²",
      "Spesifikasi Rangka: Besi Galvanis 40 x 40mm",
      "Durasi Pemasangan: 2 - 3 Jam/modul",
      "Durasi Sewa: Sesuai kebutuhan",
      "Garansi: Pemasangan",
      "Pengiriman dari Jakarta Timur",
    ],
    harga: "Informasi harga klik tombol WhatsApp",
    satuan: "",
    gambar: "assets/images/products/tenda/5-tenda-bazar.png",
  },


  // Catering
  {
    id: "cat-001",
    kategori: "catering",
    subKategori: "Nasi Box",
    nama: "Paket Nasi Box Ayam Goreng Serundeng Istimewa",
    deskripsi:
      "Paket Nasi Box Ayam Goreng Serundeng Istimewa merupakan pilihan menu catering dengan cita rasa khas Nusantara yang menghadirkan ayam goreng berbumbu rempah pilihan dengan taburan serundeng kelapa yang gurih dan renyah. Disajikan bersama pelengkap yang seimbang, menu ini cocok untuk memenuhi kebutuhan konsumsi pada berbagai kegiatan, mulai dari rapat, seminar, pelatihan, acara pemerintahan, kegiatan perusahaan, hingga acara keluarga. \n\nSeluruh hidangan dibuat menggunakan bahan baku segar dan berkualitas, diproses secara higienis, serta dikemas dalam box makanan food grade untuk menjaga kualitas, kebersihan, dan keamanan pangan hingga diterima oleh pelanggan.",
    spesifikasi: [
      "Nasi putih",
      "Ayam goreng serundeng istimewa",
      "Tahu goreng",
      "Lalapan segar",
      "Krupuk",
      "Pisang",
      "Air mineral botol 330ml",
    ],
    harga: "Rp 48.000",
    satuan: "per porsi",
    gambar: [
      "assets/images/products/catering/1-ayam-goreng-serundeng-istimewa.png",
      "assets/images/products/catering/snk.png",
    ],
  },
  {
    id: "cat-002",
    kategori: "catering",
    subKategori: "Nasi Box",
    nama: "Paket nasi Box Semur Daging Sapi Spesial",
    deskripsi:
      "Paket Nasi Box Semur Daging Sapi Spesial Nusantara merupakan menu catering premium dengan cita rasa khas Indonesia yang menghadirkan semur daging sapi berbumbu rempah dan kecap pilihan. Daging sapi dimasak hingga empuk dengan bumbu yang meresap, dipadukan dengan aneka lauk pelengkap yang lezat dan seimbang sehingga cocok untuk berbagai kebutuhan konsumsi. \n\nMenu ini sangat sesuai untuk kegiatan rapat, seminar, pelatihan, acara pemerintahan, kegiatan perusahaan, maupun acara keluarga. Seluruh hidangan diolah menggunakan bahan baku segar dan berkualitas, diproses secara higienis, serta dikemas dalam box makanan food grade untuk menjaga kualitas dan keamanan pangan.",
    spesifikasi: [
      "Nasi Putih",
      "Semur Daging Sapi Spesial",
      "Telur Balado",
      "Bihun Goreng",
      "Oseng Buncis",
      "Bakso",
      "Sambal",
      "Air Mineral Botol 330ml",
    ],
    harga: "Rp 48.000",
    satuan: "per porsi",
    gambar: [
      "assets/images/products/catering/2-semur-daging-sapi-spesial.png",
      "assets/images/products/catering/snk.png",
    ],
  },
  {
    id: "cat-003",
    kategori: "catering",
    subKategori: "Nasi Box",
    nama  : "Paket Nasi Box Ayam Goreng Serundeng Rempah",
    deskripsi:
      "Paket Nasi Box Ayam Goreng Serundeng Rempah Nusantara merupakan paket catering dengan cita rasa khas Indonesia yang menghadirkan ayam goreng berbumbu rempah pilihan dengan taburan serundeng gurih dan renyah. Disajikan bersama aneka pelengkap yang seimbang, menu ini cocok untuk memenuhi kebutuhan konsumsi pada berbagai kegiatan, seperti rapat, seminar, pelatihan, acara pemerintahan, kegiatan perusahaan, maupun acara keluarga. \n\nSeluruh menu diolah menggunakan bahan baku segar dan berkualitas, diproses secara higienis, serta dikemas dalam box makanan food grade untuk menjaga kualitas dan keamanan pangan hingga diterima oleh pelanggan.",
    spesifikasi: [
      "Nasi Putih",
      "Ayam Goreng Serundeng",
      "Tahu",
      "Tempe",
      "Sambal",
      "Lalapan Segar",
      "Air Mineral Botol 330ml",
    ],
    harga: "Rp 47.000",
    satuan: "per porsi",
    gambar: [
      "assets/images/products/catering/3-ayam-goreng-serundeng-rempah.png",
      "assets/images/products/catering/snk.png",
    ],
  },
  {
    id: "cat-004",
    kategori: "catering",
    subKategori: "Nasi Box",
    nama: "Paket Nasi Box Ayam Bakar Spesial Nusantara",
    deskripsi:
      "Paket Nasi Box Ayam Bakar Spesial Nusantara merupakan pilihan menu catering dengan cita rasa khas Indonesia yang diolah menggunakan bumbu rempah pilihan dan dipanggang hingga menghasilkan aroma yang menggugah selera. Cocok untuk berbagai kebutuhan, seperti rapat, pelatihan, seminar, kegiatan instansi, acara kantor, maupun acara keluarga. \n\nSetiap paket disiapkan menggunakan bahan baku segar, dikemas dalam box makanan food grade, dan diproses secara higienis untuk menjaga kualitas serta keamanan pangan.",
      spesifikasi: [
        "Nasi Putih",
        "Ayam Bakar Spesial Nusantara",
        "Bihun Goreng",
        "Kentang Balado",
        "Sambal",
        "Lalapan Segar",
        "Kerupuk",
        "Pisang",
        "Air Mineral Botol 330ml",
      ],
    harga: "Rp 47.000",
    satuan: "per porsi",
    gambar: [
      "assets/images/products/catering/4-ayam-bakar-spesial-nusa.png",
      "assets/images/products/catering/snk.png",
    ],
  },
  {
    id: "cat-005",
    kategori: "catering",
    subKategori: "Prasmanan",
    nama: "Paket Prasmanan - Sajian Lengkap untuk Berbagai Acara",
    deskripsi:
      "Paket Catering Prasmanan merupakan layanan penyediaan hidangan lengkap untuk berbagai kebutuhan acara, seperti rapat, seminar, pernikahan, syukuran, pengajian, acara kantor, dan kegiatan keluarga. Menu disajikan secara prasmanan dengan pilihan hidangan yang beragam, mulai dari nasi, olahan ayam, daging sapi, ikan, sayuran, sup, aneka mie dan pasta, jajanan, dessert, hingga berbagai pilihan minuman. \n\nPilihan menu dapat disesuaikan dengan kebutuhan dan konsep acara. Penyajian makanan dilakukan dengan memperhatikan kualitas, kebersihan, cita rasa, dan kerapian sehingga siap dinikmati oleh para tamu. Paket dapat disesuaikan berdasarkan jumlah porsi, pilihan menu, waktu, dan lokasi acara sesuai dengan ketentuan pemesanan.",
    spesifikasi: [
      "Pilihan Nasi",
      "Olahan Sup",
      "Olahan Daging Ayam",
      "Olahan Daging Sapi",
      "Olahan Ikan",
      "Olahan Sayurang",
      "Olahan Seafood",
      "Aneka Mie",
      "Aneka Jajanan dan Kudapan",
      "Aneka Makanan Penutup (dessert)",
      "Aneka Minuman",
    ],
    harga: "Harga menyesuaikan pilihan menu",
    satuan: "",
    gambar: [
      "assets/images/products/catering/5.1-prasmanan-1.png",
      "assets/images/products/catering/5.2-prasmanan-2.png",
      "assets/images/products/catering/5.3-snk-prasmanan.png",
    ],
  },
  {
    id: "cat-006",
    kategori: "catering",
    subKategori: "Snack Box",
    nama: "Paket Snack Box Hemat - Pilihan Lezat Harga Bersahabat",
    deskripsi:
      "Paket Snack Box Hemat merupakan paket konsumsi yang dirancang untuk memenuhi kebutuhan makanan ringan pada berbagai kegiatan instansi pemerintah, BUMN, swasta, maupun organisasi. Setiap paket berisi Risoles, Kroket, Kue Lumpur Kentang, dan Air Mineral yang dibuat menggunakan bahan berkualitas, diproses secara higienis, serta dikemas rapi dalam snack box sehingga praktis untuk disajikan. \n\nKombinasi menu gurih dan manis ini cocok untuk mendukung berbagai kegiatan seperti rapat koordinasi, rapat kerja, seminar, bimbingan teknis (Bimtek), sosialisasi, workshop, pelatihan, Focus Group Discussion (FGD), konsultasi publik, serta kegiatan kedinasan lainnya.",
    spesifikasi: [
      "Risoles",
      "Kroket",
      "Kue Lumpur",
      "Kentang",
      "Air Mineral Botol 330ml",
    ],
    harga: "Rp 18.000",
    satuan: "per porsi",
    gambar: [
      "assets/images/products/catering/6-snack-hemat.png",
      "assets/images/products/catering/snk.png",
    ],
  },
  {
    id: "cat-007",
    kategori: "catering",
    subKategori: "Snack Box",
    nama: "Paket Snack Box Regular - Lengkap, Lezat & Praktis",
    deskripsi:
      "Paket Snack Box Reguler merupakan pilihan tepat untuk memenuhi kebutuhan konsumsi dalam berbagai acara, mulai dari rapat kantor, seminar, pelatihan, pengajian, arisan, syukuran, hingga acara keluarga. Setiap paket disiapkan menggunakan bahan-bahan berkualitas, diolah secara higienis, dan dikemas dengan rapi untuk memberikan pengalaman menikmati sajian yang praktis dan lezat. \n\nKami melayani pemesanan untuk berbagai skala acara, baik dalam jumlah kecil maupun besar, dengan proses yang mudah, pelayanan profesional, serta pengiriman yang tepat waktu. Jadikan setiap acara lebih berkesan dengan Paket Snack Box Reguler yang praktis, lezat, dan berkualitas.\n\n",
    spesifikasi: [
      "Roti Sobek Keju",
      "Schotel Keju",
      "Risoles Mayones",
      "Air Mineral Cleo 330ml",
    ],
    harga: "Rp 18.000",
    satuan: "per porsi",
    gambar: [
      "assets/images/products/catering/7-snack-regular.png",
      "assets/images/products/catering/snk.png",
    ],
  },
  {
    id: "cat-008",
    kategori: "catering",
    subKategori: "Snack Box",
    nama: "Paket Snack Box Best Seller - Menu Favorit dengan Cita Rasa Berkualitas",
    deskripsi:
      "Menu Favorit dengan Cita Rasa Berkualitas menghadirkan sajian berkualitas untuk setiap momen spesial bersama Paket Snack Box Best Seller. Paket ini berisi perpaduan camilan manis dan gurih yang dibuat dari bahan pilihan, dikemas secara higienis, dan disajikan dengan tampilan yang menarik sehingga cocok untuk berbagai jenis acara. \n\nPaket Snack Box Best Seller sangat cocok untuk rapat kantor, seminar, pelatihan, pengajian, arisan, syukuran, ulang tahun, wisuda, hingga berbagai acara keluarga dan perusahaan. Kami melayani pemesanan dalam jumlah kecil maupun besar dengan kemasan rapi, kualitas terjaga, serta pengiriman tepat waktu agar acara Anda berjalan lancar.",
    spesifikasi: [
      "Roti Premium",
      "Dessert Box",
      "Kue Talam Pandan",
      "Kacang Kemasan",
      "Teh Kotak",
    ],
    harga: "Rp 18.000",
    satuan: "per porsi",
    gambar: [
      "assets/images/products/catering/8-snack-best-seller.png",
      "assets/images/products/catering/snk.png",
    ],
  },
];